### ISSUE TITLE
Mocklogs[0] is undefined - test failing with this error starting on exercise 07/05

### ISSUE THREAD

**Issue by Creeland** [epicweb-dev/react-fundamentals#374] opened 2024-08-30 23:36 UTC
https://www.loom.com/share/2aefad2830e04c938bd694408ee2ffcd?sid=144fb378-e17c-4185-a14c-adf3b4756649

This test fails with the error Mocklogs[0] is undefined when tests are initially ran but after a hot reload the test passes. 

I think there's some kind of issue with the mock console.log. Maybe the way that the stack is checking for action?

**Comment by kentcdodds** [comment] 2024-08-31 00:10
Hmmm... I'm not able to reproduce this issue.

There's no hot reloading. It refreshes the iframe so there's no state shared between runs.

People should not be opening or editing the tests unless they are contributing to them so I'm not too concerned about this. And the tests are a little unique so I'm not terribly surprised they're not working perfectly so I'm definitely open to having them improved, but because I can't reproduce this one I'm going to close it.

**Closed by kentcdodds** 2024-08-31 00:10 UTC
